name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '6.0.x'
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-api-image:
    name: Push API Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Multi-Arch API Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/donghongfei/firecrawl-api:latest \
            --push \
            --secret id=SENTRY_AUTH_TOKEN \
            ./apps/api

  push-playwright-image:
    name: Push Playwright Service Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Multi-Arch Playwright Service Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/donghongfei/firecrawl-playwright-service:latest \
            --push \
            --secret id=SENTRY_AUTH_TOKEN \
            ./apps/playwright-service
